"""empty message

Revision ID: 0435fd71525c
Revises: d4cdc5e5cead
Create Date: 2025-12-02 17:21:04.648919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0435fd71525c'
down_revision = 'd4cdc5e5cead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('brand',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('batch_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('mrp',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('mrp',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('batch_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('brand',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('item_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
