"""empty message

Revision ID: 047fada24826
Revises: 0435fd71525c
Create Date: 2025-12-04 12:01:01.491725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '047fada24826'
down_revision = '0435fd71525c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('batch_code'))
        batch_op.drop_column('item_name')
        batch_op.drop_column('batch_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_code', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('item_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.create_index(batch_op.f('batch_code'), ['batch_code'], unique=True)

    # ### end Alembic commands ###
