"""empty message

Revision ID: 1e887356b390
Revises: 4a3ce6315cb3
Create Date: 2025-11-19 11:43:24.709178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e887356b390'
down_revision = '4a3ce6315cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_esi_pf_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('leave', sa.Float(), nullable=True),
    sa.Column('grace', sa.Float(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('salary_payable', sa.Float(), nullable=True),
    sa.Column('loan', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('no_esi_pf_salary')
    # ### end Alembic commands ###
