"""empty message

Revision ID: 201907cc6760
Revises: 6b6220c5a083
Create Date: 2026-01-27 11:27:03.999140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201907cc6760'
down_revision = '6b6220c5a083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
