"""empty message

Revision ID: 26a148e4b780
Revises: 8f2e8dc38bfe
Create Date: 2026-01-02 13:21:13.641429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a148e4b780'
down_revision = '8f2e8dc38bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('supplier_description', sa.String(length=500), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
