"""empty message

Revision ID: 27888a3c0b14
Revises: e916abe47a7a
Create Date: 2026-01-04 23:09:10.235599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27888a3c0b14'
down_revision = 'e916abe47a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_remarks', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rejection_remarks', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('rejected_date')
        batch_op.drop_column('approved_date')
        batch_op.drop_column('rejection_remarks')
        batch_op.drop_column('approval_remarks')

    # ### end Alembic commands ###
