"""empty message

Revision ID: 2cf78d259c72
Revises: cd5526ff6b51
Create Date: 2026-02-02 20:23:09.203728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf78d259c72'
down_revision = 'cd5526ff6b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_saved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('saved_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.drop_column('saved_on')
        batch_op.drop_column('is_saved')

    # ### end Alembic commands ###
