"""empty message

Revision ID: 2dd1a5e2a84f
Revises: 7c513b5c51cd
Create Date: 2026-02-08 17:07:21.450067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd1a5e2a84f'
down_revision = '7c513b5c51cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.drop_column('updated_on')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
