"""empty message

Revision ID: 32193e657356
Revises: 99e42a8f8994
Create Date: 2026-01-07 18:00:51.925387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32193e657356'
down_revision = '99e42a8f8994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_order_item_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_order_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sales_order_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sales_order_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sales_order_remark', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['sales_order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sales_order_remark')
        batch_op.drop_column('sales_order_status')
        batch_op.drop_column('sales_order_date')
        batch_op.drop_column('sales_order_number')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('sales_order_item_status')

    # ### end Alembic commands ###
