"""empty message

Revision ID: 3c2464b67504
Revises: 9e031a7690d6
Create Date: 2025-12-09 10:01:05.577184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c2464b67504'
down_revision = '9e031a7690d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('brand_code', sa.String(length=100), nullable=True),
    sa.Column('brand_description', sa.String(length=255), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mrp', mysql.FLOAT(), nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('brand_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('brand_description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('product')
    # ### end Alembic commands ###
