"""empty message

Revision ID: 3c5d7ad06139
Revises: c0246fb1fe80
Create Date: 2025-11-20 10:46:48.984579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5d7ad06139'
down_revision = 'c0246fb1fe80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_esipf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('leave', sa.Float(), nullable=True),
    sa.Column('grace', sa.Float(), nullable=True),
    sa.Column('working_days', sa.Float(), nullable=True),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('salary_input', sa.Float(), nullable=True),
    sa.Column('monthly_salary', sa.Float(), nullable=True),
    sa.Column('basic', sa.Float(), nullable=True),
    sa.Column('hra', sa.Float(), nullable=True),
    sa.Column('conv', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('basic_conv', sa.Float(), nullable=True),
    sa.Column('restricted_basic', sa.Float(), nullable=True),
    sa.Column('pf', sa.Float(), nullable=True),
    sa.Column('esi', sa.Float(), nullable=True),
    sa.Column('loan', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('ptax', sa.Float(), nullable=True),
    sa.Column('total_ded', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_esipf')
    # ### end Alembic commands ###
