"""empty message

Revision ID: 408d22c58314
Revises: 652bde271b8e
Create Date: 2026-02-07 14:48:53.250330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408d22c58314'
down_revision = '652bde271b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_setter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_setter')
    # ### end Alembic commands ###
