"""empty message

Revision ID: 4371d0ebcb14
Revises: 26a148e4b780
Create Date: 2026-01-03 12:03:53.744302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4371d0ebcb14'
down_revision = '26a148e4b780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('split_percentage', sa.Float(), nullable=True),
    sa.Column('split_months', sa.Integer(), nullable=True),
    sa.Column('deduction_start', sa.String(length=10), nullable=True),
    sa.Column('deduction_schedule', sa.Text(), nullable=True),
    sa.Column('per_month_deduction', sa.Float(), nullable=True),
    sa.Column('total_deduction_months', sa.Integer(), nullable=True),
    sa.Column('deduction_start_month', sa.String(length=50), nullable=True),
    sa.Column('deduction_end_month', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount_deducted', sa.Float(), nullable=True),
    sa.Column('amount_remaining', sa.Float(), nullable=True),
    sa.Column('deductions_completed', sa.Integer(), nullable=True),
    sa.Column('deduct_month', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advances_email'), ['email'], unique=False)

    op.drop_table('advance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('deduct_month', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advances_email'))

    op.drop_table('advances')
    # ### end Alembic commands ###
