"""empty message

Revision ID: 4936cc4be2a9
Revises: fd37d88b4a2d
Create Date: 2025-12-10 15:53:33.737551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4936cc4be2a9'
down_revision = 'fd37d88b4a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deduct_month', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advance', schema=None) as batch_op:
        batch_op.drop_column('deduct_month')

    # ### end Alembic commands ###
