"""empty message

Revision ID: 4c0208742e53
Revises: 3c5d7ad06139
Create Date: 2025-11-20 14:11:33.662978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0208742e53'
down_revision = '3c5d7ad06139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('width', sa.String(length=50), nullable=True),
    sa.Column('batch_code', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grn')
    # ### end Alembic commands ###
