"""empty message

Revision ID: 5c38ba6343c1
Revises: ac238cc92a0e
Create Date: 2025-12-13 19:55:00.350016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c38ba6343c1'
down_revision = 'ac238cc92a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_part_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hsn_sac', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cut_width', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mrp', sa.String(length=50), nullable=True))
        batch_op.drop_column('qty')
        batch_op.drop_column('width')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('qty', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('mrp')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')
        batch_op.drop_column('cut_width')
        batch_op.drop_column('hsn_sac')
        batch_op.drop_column('supplier_part_no')

    # ### end Alembic commands ###
