"""empty message

Revision ID: 652bde271b8e
Revises: 2cf78d259c72
Create Date: 2026-02-04 22:42:24.531547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '652bde271b8e'
down_revision = '2cf78d259c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.drop_column('save_status')
        batch_op.drop_column('last_save_attempt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_save_attempt', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('save_status', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
