"""empty message

Revision ID: 66ab21ecbf82
Revises: e158bd3ae1a0
Create Date: 2025-12-11 17:43:52.658159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ab21ecbf82'
down_revision = 'e158bd3ae1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('review_status')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
