"""empty message

Revision ID: 6b6220c5a083
Revises: 46f9f87faccb
Create Date: 2026-01-23 16:43:05.920517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6220c5a083'
down_revision = '46f9f87faccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_number', sa.String(length=100), nullable=False),
    sa.Column('issuer_name', sa.String(length=200), nullable=True),
    sa.Column('issuer_address', sa.Text(), nullable=True),
    sa.Column('issuer_phone', sa.String(length=15), nullable=True),
    sa.Column('issuer_email', sa.String(length=100), nullable=True),
    sa.Column('issuer_gstin', sa.String(length=15), nullable=True),
    sa.Column('issuer_state_code', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_pincode', sa.String(length=10), nullable=True),
    sa.Column('company_gstin', sa.String(length=15), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_mobile', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquiry_number')
    )
    op.create_table('enquiry_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cut_width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('count', sa.Float(), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('brand_code', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('item_status', sa.String(length=50), nullable=True),
    sa.Column('customer_description', sa.Text(), nullable=True),
    sa.Column('customer_requirements', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enquiry_item')
    op.drop_table('enquiry')
    # ### end Alembic commands ###
