"""empty message

Revision ID: 7c513b5c51cd
Revises: 408d22c58314
Create Date: 2026-02-08 04:51:31.027513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c513b5c51cd'
down_revision = '408d22c58314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_deducted', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('deducted_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.drop_column('deducted_on')
        batch_op.drop_column('stock_deducted')

    # ### end Alembic commands ###
