"""empty message

Revision ID: 8f2e8dc38bfe
Revises: 8f95d3becaa0
Create Date: 2025-12-30 16:53:15.391122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2e8dc38bfe'
down_revision = '8f95d3becaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('gst_number')

    # ### end Alembic commands ###
