"""empty message

Revision ID: 8f95d3becaa0
Revises: acb53e5dbe38
Create Date: 2025-12-22 21:54:37.803497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f95d3becaa0'
down_revision = 'acb53e5dbe38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('packing_charges')
        batch_op.drop_column('other_charges')
        batch_op.drop_column('count')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('total_packing')
        batch_op.drop_column('total_other')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_other', mysql.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_packing', mysql.DECIMAL(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('other_charges', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('packing_charges', mysql.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
