"""empty message

Revision ID: 929ea84f04bb
Revises: b71ed312cd17
Create Date: 2026-01-07 11:54:09.110992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '929ea84f04bb'
down_revision = 'b71ed312cd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIRST: Handle GRN table NULL values before making columns NOT NULL
    op.execute("UPDATE grn SET invoice_number = 'NOT_AVAILABLE' WHERE invoice_number IS NULL OR invoice_number = ''")
    op.execute("UPDATE grn SET invoice_date = '2000-01-01' WHERE invoice_date IS NULL OR invoice_date = ''")
    op.execute("UPDATE grn SET item_name = 'UNKNOWN' WHERE item_name IS NULL OR item_name = ''")
    op.execute("UPDATE grn SET buy_price = 0.0 WHERE buy_price IS NULL")
    op.execute("UPDATE grn SET batch_code = 'NOT_AVAILABLE' WHERE batch_code IS NULL OR batch_code = ''")
    
    # Now modify GRN table
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('invoice_date',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('item_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('buy_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('batch_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('customer_part_no')
        batch_op.drop_column('customer_description')

    # SECOND: Handle tasks table - add columns as nullable first
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('batch_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completedAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelledAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
    
    # Set default values for existing tasks
    op.execute("""
        UPDATE tasks 
        SET po_number = CONCAT('PO-', id, '-', DATE_FORMAT(createdAt, '%Y%m%d'))
        WHERE po_number IS NULL OR po_number = ''
    """)
    
    # Copy title to po_number for existing tasks if title exists
    op.execute("""
        UPDATE tasks 
        SET po_number = CONCAT('TASK-', title)
        WHERE title IS NOT NULL AND title != '' AND po_number LIKE 'PO-%'
    """)
    
    # Set updatedAt for existing tasks
    op.execute("UPDATE tasks SET updatedAt = createdAt WHERE updatedAt IS NULL")
    
    # Now make po_number NOT NULL
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('po_number',
               existing_type=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
        
        # Copy po_number back to title before dropping
        op.execute("UPDATE tasks SET title = po_number WHERE title IS NULL")
        
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelledAt')
        batch_op.drop_column('completedAt')
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('batch_no')
        batch_op.drop_column('brand_code')
        batch_op.drop_column('company_address')
        batch_op.drop_column('po_number')

    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_description', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('customer_part_no', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('batch_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('buy_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('item_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('invoice_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###