"""empty message

Revision ID: 92ca2ef0fcf7
Revises: 
Create Date: 2026-02-09 12:19:31.090447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ca2ef0fcf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('split_percentage', sa.Float(), nullable=True),
    sa.Column('split_months', sa.Integer(), nullable=True),
    sa.Column('deduction_start', sa.String(length=10), nullable=True),
    sa.Column('deduction_schedule', sa.Text(), nullable=True),
    sa.Column('per_month_deduction', sa.Float(), nullable=True),
    sa.Column('total_deduction_months', sa.Integer(), nullable=True),
    sa.Column('deduction_start_month', sa.String(length=50), nullable=True),
    sa.Column('deduction_end_month', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount_deducted', sa.Float(), nullable=True),
    sa.Column('amount_remaining', sa.Float(), nullable=True),
    sa.Column('deductions_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advances_email'), ['email'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('check_in', sa.String(length=20), nullable=True),
    sa.Column('check_out', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('device_in', sa.JSON(), nullable=True),
    sa.Column('device_out', sa.JSON(), nullable=True),
    sa.Column('location_in', sa.JSON(), nullable=True),
    sa.Column('location_out', sa.JSON(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('present', sa.Float(), nullable=True),
    sa.Column('absent', sa.Float(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casual_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('leave', sa.Float(), nullable=True),
    sa.Column('grace', sa.Float(), nullable=True),
    sa.Column('working_days', sa.Float(), nullable=True),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('salary_payable', sa.Float(), nullable=True),
    sa.Column('loan', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=False),
    sa.Column('pin_code', sa.String(length=10), nullable=False),
    sa.Column('industry_segment', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_mobile', sa.String(length=15), nullable=False),
    sa.Column('customer_email', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('personal_mobile', sa.String(length=15), nullable=False),
    sa.Column('personal_email', sa.String(length=100), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_setter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('doj', sa.String(length=50), nullable=True),
    sa.Column('empType', sa.String(length=50), nullable=True),
    sa.Column('userType', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('altContact', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('aadhar', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('panAttachment', sa.String(length=255), nullable=True),
    sa.Column('aadharAttachment', sa.String(length=255), nullable=True),
    sa.Column('esiPfStatus', sa.String(length=20), nullable=True),
    sa.Column('createdBy', sa.String(length=120), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('grn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_address', sa.String(length=500), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_mobile', sa.String(length=15), nullable=True),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('supplier_description', sa.String(length=500), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('brand_code', sa.String(length=50), nullable=True),
    sa.Column('brand_description', sa.String(length=500), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('width', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('industrialsegmentation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('no_esi_pf_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('leave', sa.Float(), nullable=True),
    sa.Column('grace', sa.Float(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('salary_payable', sa.Float(), nullable=True),
    sa.Column('loan', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('brand_code', sa.String(length=100), nullable=True),
    sa.Column('brand_description', sa.String(length=255), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_esipf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('leave', sa.Float(), nullable=True),
    sa.Column('grace', sa.Float(), nullable=True),
    sa.Column('working_days', sa.Float(), nullable=True),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('salary_input', sa.Float(), nullable=True),
    sa.Column('monthly_salary', sa.Float(), nullable=True),
    sa.Column('basic', sa.Float(), nullable=True),
    sa.Column('hra', sa.Float(), nullable=True),
    sa.Column('conv', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('basic_conv', sa.Float(), nullable=True),
    sa.Column('restricted_basic', sa.Float(), nullable=True),
    sa.Column('pf', sa.Float(), nullable=True),
    sa.Column('esi', sa.Float(), nullable=True),
    sa.Column('loan', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('ptax', sa.Float(), nullable=True),
    sa.Column('total_ded', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_sold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('sold_date', sa.String(length=30), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('sold_remarks', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('saved_on', sa.DateTime(), nullable=True),
    sa.Column('stock_deducted', sa.String(length=10), nullable=False),
    sa.Column('deducted_on', sa.DateTime(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=100), nullable=True),
    sa.Column('invoice_remarks', sa.String(length=500), nullable=True),
    sa.Column('invoice_amount', sa.Float(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('production_end_date', sa.String(length=30), nullable=True),
    sa.Column('production_start_date', sa.String(length=30), nullable=True),
    sa.Column('production_status', sa.String(length=100), nullable=True),
    sa.Column('quality_check', sa.String(length=100), nullable=True),
    sa.Column('thickness', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('auto_calculate_count', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('batch_code', sa.String(length=100), nullable=True),
    sa.Column('brand_code', sa.String(length=50), nullable=True),
    sa.Column('brand_description', sa.String(length=255), nullable=True),
    sa.Column('hsn', sa.String(length=50), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('dueDate', sa.String(length=50), nullable=True),
    sa.Column('assignedTo', sa.String(length=100), nullable=True),
    sa.Column('assignedBy', sa.String(length=100), nullable=True),
    sa.Column('assignedByEmail', sa.String(length=100), nullable=True),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('quotation_number', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('brand_code', sa.String(length=100), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('cut_width', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('mrp', sa.String(length=50), nullable=True),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('thickness', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_check', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('invoice_amount', sa.Float(), nullable=True),
    sa.Column('invoice_remarks', sa.Text(), nullable=True),
    sa.Column('invoice_created_at', sa.DateTime(), nullable=True),
    sa.Column('production_start_date', sa.DateTime(), nullable=True),
    sa.Column('production_end_date', sa.DateTime(), nullable=True),
    sa.Column('production_status', sa.String(length=50), nullable=True),
    sa.Column('quality_check', sa.String(length=50), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.Column('cancelledAt', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('visit_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('company_address', sa.String(length=250), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('industry_segment', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_mobile', sa.String(length=15), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('allow_access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_number', sa.String(length=100), nullable=False),
    sa.Column('issuer_name', sa.String(length=200), nullable=True),
    sa.Column('issuer_address', sa.Text(), nullable=True),
    sa.Column('issuer_phone', sa.String(length=15), nullable=True),
    sa.Column('issuer_email', sa.String(length=100), nullable=True),
    sa.Column('issuer_gstin', sa.String(length=15), nullable=True),
    sa.Column('issuer_state_code', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_pincode', sa.String(length=10), nullable=True),
    sa.Column('company_gstin', sa.String(length=15), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_mobile', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquiry_number')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_address', sa.String(length=500), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_mobile', sa.String(length=15), nullable=True),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('supplier_description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_remarks', sa.String(length=500), nullable=True),
    sa.Column('rejection_remarks', sa.String(length=500), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('rejected_date', sa.DateTime(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_gstin', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('issuer_details', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('sales_order_number', sa.String(length=50), nullable=True),
    sa.Column('sales_order_date', sa.DateTime(), nullable=True),
    sa.Column('sales_order_status', sa.String(length=20), nullable=True),
    sa.Column('sales_order_remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requote_note', sa.Text(), nullable=True),
    sa.Column('original_quote_id', sa.Integer(), nullable=True),
    sa.Column('requote_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number'),
    sa.UniqueConstraint('sales_order_number')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cut_width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('count', sa.Float(), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('brand_code', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('customer_description', sa.Text(), nullable=True),
    sa.Column('customer_requirements', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cut_width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('item_status', sa.String(length=20), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('sales_order_created', sa.Boolean(), nullable=True),
    sa.Column('sales_order_remark', sa.Text(), nullable=True),
    sa.Column('sales_order_date', sa.DateTime(), nullable=True),
    sa.Column('sales_order_item_status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_before_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_after_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('item_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_items')
    op.drop_table('enquiry_items')
    op.drop_table('user_permissions')
    op.drop_table('quotations')
    op.drop_table('purchase_orders')
    op.drop_table('enquiries')
    op.drop_table('access_controls')
    op.drop_table('visit_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('user_types')
    op.drop_table('tasks')
    op.drop_table('stocks')
    op.drop_table('stock_sold')
    op.drop_table('salary_esipf')
    op.drop_table('product')
    op.drop_table('no_esi_pf_salary')
    op.drop_table('modules')
    op.drop_table('industrialsegmentation')
    op.drop_table('holidays')
    op.drop_table('grn')
    op.drop_table('employees')
    op.drop_table('designations')
    op.drop_table('departments')
    op.drop_table('dashboard_setter')
    op.drop_table('companies')
    op.drop_table('casual_salary')
    op.drop_table('attendance_summary')
    op.drop_table('attendance')
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advances_email'))

    op.drop_table('advances')
    # ### end Alembic commands ###
