"""empty message

Revision ID: 99e42a8f8994
Revises: 929ea84f04bb
Create Date: 2026-01-07 17:19:27.300283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e42a8f8994'
down_revision = '929ea84f04bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_order_created', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sales_order_remark', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sales_order_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('sales_order_date')
        batch_op.drop_column('sales_order_remark')
        batch_op.drop_column('sales_order_created')

    # ### end Alembic commands ###
