"""empty message

Revision ID: 9e031a7690d6
Revises: adcf4f50bd60
Create Date: 2025-12-09 09:59:37.697833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e031a7690d6'
down_revision = 'adcf4f50bd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('brand_code', sa.String(length=50), nullable=True),
    sa.Column('brand_description', sa.String(length=255), nullable=True),
    sa.Column('hsn', sa.String(length=50), nullable=True),
    sa.Column('batch_code', sa.String(length=100), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('width', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('brand', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('brand_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('brand_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hsn', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('batch_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mrp', mysql.FLOAT(), nullable=True),
    sa.Column('buy_price', mysql.FLOAT(), nullable=True),
    sa.Column('width', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('gst', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('stocks')
    # ### end Alembic commands ###
