"""empty message

Revision ID: aaf815bb5042
Revises: f499b6be49ce
Create Date: 2025-11-27 11:30:14.177139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaf815bb5042'
down_revision = 'f499b6be49ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('customer_part_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('length', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('buy_price', sa.Float(), nullable=True))
        batch_op.alter_column('batch_code',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('qty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('batch_code',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('buy_price')
        batch_op.drop_column('length')
        batch_op.drop_column('customer_description')
        batch_op.drop_column('customer_part_no')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
