"""empty message

Revision ID: ac238cc92a0e
Revises: cf7247b96916
Create Date: 2025-12-13 19:21:07.555584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac238cc92a0e'
down_revision = 'cf7247b96916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quotation_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('product_code')
        batch_op.drop_column('batch_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_code', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('product_code', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('item_name')
        batch_op.drop_column('item_id')
        batch_op.drop_column('company_name')
        batch_op.drop_column('quotation_number')
        batch_op.drop_column('quotation_id')

    # ### end Alembic commands ###
