"""empty message

Revision ID: acb53e5dbe38
Revises: c9d9b4adf40a
Create Date: 2025-12-22 21:34:00.974112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb53e5dbe38'
down_revision = 'c9d9b4adf40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('packing_charges', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('other_charges', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_packing', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_other', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('total_other')
        batch_op.drop_column('total_packing')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('other_charges')
        batch_op.drop_column('packing_charges')
        batch_op.drop_column('count')

    # ### end Alembic commands ###
