"""empty message

Revision ID: adcf4f50bd60
Revises: 047fada24826
Create Date: 2025-12-08 21:55:20.664305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcf4f50bd60'
down_revision = '047fada24826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('brand_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('brand_description')
        batch_op.drop_column('brand_code')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
