"""empty message

Revision ID: bdcf26952866
Revises: 64db8a4a6e84
Create Date: 2025-11-17 11:16:38.389369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcf26952866'
down_revision = '64db8a4a6e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('allow_access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_control')
    # ### end Alembic commands ###
