"""empty message

Revision ID: c0246fb1fe80
Revises: 8a1f7af67963
Create Date: 2025-11-19 17:44:39.385416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0246fb1fe80'
down_revision = '8a1f7af67963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casual_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('leave', sa.Float(), nullable=True),
    sa.Column('grace', sa.Float(), nullable=True),
    sa.Column('working_days', sa.Float(), nullable=True),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('salary_payable', sa.Float(), nullable=True),
    sa.Column('loan', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casual_salary')
    # ### end Alembic commands ###
