"""empty message

Revision ID: c9d9b4adf40a
Revises: 30f050c430cb
Create Date: 2025-12-22 20:49:06.554495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9d9b4adf40a'
down_revision = '30f050c430cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', mysql.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
