"""empty message

Revision ID: cd5526ff6b51
Revises: f3cbc1c32055
Create Date: 2026-02-02 00:14:35.475832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd5526ff6b51'
down_revision = 'f3cbc1c32055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sold_date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sold_remarks', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('hsn_sac', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invoice_remarks', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('invoice_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mrp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('material_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('production_end_date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('production_start_date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('production_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quality_check', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('thickness', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.String(length=30), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('sold_qty')
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('sold_qty', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('date', mysql.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('due_date')
        batch_op.drop_column('thickness')
        batch_op.drop_column('quality_check')
        batch_op.drop_column('production_status')
        batch_op.drop_column('production_start_date')
        batch_op.drop_column('production_end_date')
        batch_op.drop_column('material_type')
        batch_op.drop_column('mrp')
        batch_op.drop_column('invoice_amount')
        batch_op.drop_column('invoice_remarks')
        batch_op.drop_column('hsn_sac')
        batch_op.drop_column('sold_remarks')
        batch_op.drop_column('sold_date')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')
        batch_op.drop_column('company_name')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
