"""empty message

Revision ID: cf7247b96916
Revises: 66ab21ecbf82
Create Date: 2025-12-13 14:48:39.079710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7247b96916'
down_revision = '66ab21ecbf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requote_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('original_quote_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requote_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('requote_date')
        batch_op.drop_column('original_quote_id')
        batch_op.drop_column('requote_note')

    # ### end Alembic commands ###
