"""empty message

Revision ID: d5ce79c30e16
Revises: 201907cc6760
Create Date: 2026-01-29 12:26:46.593514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5ce79c30e16'
down_revision = '201907cc6760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry_item', schema=None) as batch_op:
        batch_op.drop_column('item_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_status', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
