"""empty message

Revision ID: e158bd3ae1a0
Revises: 4936cc4be2a9
Create Date: 2025-12-11 15:45:38.593197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e158bd3ae1a0'
down_revision = '4936cc4be2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_column('item_status')

    # ### end Alembic commands ###
