"""empty message

Revision ID: f05b003c2467
Revises: 12e7a1b800a0
Create Date: 2026-03-24 15:11:43.503500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05b003c2467'
down_revision = '12e7a1b800a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_partial', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delivery_sequence', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('original_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivered_before', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.drop_column('delivered_before')
        batch_op.drop_column('original_quantity')
        batch_op.drop_column('delivery_sequence')
        batch_op.drop_column('is_partial')

    # ### end Alembic commands ###
