"""empty message

Revision ID: f3cbc1c32055
Revises: d5ce79c30e16
Create Date: 2026-01-29 14:51:41.031649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3cbc1c32055'
down_revision = 'd5ce79c30e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_number', sa.String(length=100), nullable=False),
    sa.Column('issuer_name', sa.String(length=200), nullable=True),
    sa.Column('issuer_address', sa.Text(), nullable=True),
    sa.Column('issuer_phone', sa.String(length=15), nullable=True),
    sa.Column('issuer_email', sa.String(length=100), nullable=True),
    sa.Column('issuer_gstin', sa.String(length=15), nullable=True),
    sa.Column('issuer_state_code', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_pincode', sa.String(length=10), nullable=True),
    sa.Column('company_gstin', sa.String(length=15), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_mobile', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquiry_number')
    )
    op.create_table('enquiry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('supplier_part_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cut_width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('count', sa.Float(), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('brand_code', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('customer_description', sa.Text(), nullable=True),
    sa.Column('customer_requirements', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('enquiry_item')
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('enquiry_number'))

    op.drop_table('enquiry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enquiry_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('issuer_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('issuer_address', mysql.TEXT(), nullable=True),
    sa.Column('issuer_phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('issuer_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('issuer_gstin', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('issuer_state_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('company_address', mysql.TEXT(), nullable=True),
    sa.Column('company_pincode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('company_gstin', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('contact_person', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('contact_mobile', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('contact_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('total_items', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_quantity', mysql.FLOAT(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('time', mysql.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='enquiry_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('enquiry_number'), ['enquiry_number'], unique=True)

    op.create_table('enquiry_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hsn_sac', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('supplier_part_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('cut_width', mysql.FLOAT(), nullable=True),
    sa.Column('length', mysql.FLOAT(), nullable=True),
    sa.Column('count', mysql.FLOAT(), nullable=True),
    sa.Column('batch_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('brand_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('customer_description', mysql.TEXT(), nullable=True),
    sa.Column('customer_requirements', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('enquiry_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], name=op.f('enquiry_item_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('enquiry_items')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
