"""empty message

Revision ID: f499b6be49ce
Revises: 4c0208742e53
Create Date: 2025-11-20 15:35:37.214234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f499b6be49ce'
down_revision = '4c0208742e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_sold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('sold_qty', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_sold')
    # ### end Alembic commands ###
