"""empty message

Revision ID: f4bc8ae13766
Revises: 5c38ba6343c1
Create Date: 2025-12-14 19:21:09.414530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bc8ae13766'
down_revision = '5c38ba6343c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('thickness', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invoice_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('invoice_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('invoice_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('production_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('production_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('production_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quality_check', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('quality_check')
        batch_op.drop_column('production_status')
        batch_op.drop_column('production_end_date')
        batch_op.drop_column('production_start_date')
        batch_op.drop_column('invoice_created_at')
        batch_op.drop_column('invoice_remarks')
        batch_op.drop_column('invoice_amount')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('thickness')
        batch_op.drop_column('material_type')

    # ### end Alembic commands ###
