"""empty message

Revision ID: f9052fbce39f
Revises: 4371d0ebcb14
Create Date: 2026-01-04 20:43:33.210225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9052fbce39f'
down_revision = '4371d0ebcb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.drop_column('deduct_month')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('company_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_mobile', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gst_number', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.drop_column('supplier_name')
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('supplier_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gst_number')
        batch_op.drop_column('department')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_mobile')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('company_address')
        batch_op.drop_column('company_name')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deduct_month', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
